# Generated by Django 5.0.6 on 2024-07-30 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_booking_phone_number_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numeric and up to 13 digits', regex='^\\d{1,13}$')]),
        ),
    ]
