# Generated by Django 5.0.6 on 2024-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_booking_new_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='new_reservation',
            field=models.BooleanField(default=True, help_text='Indicates if the reservation is new'),
        ),
    ]
