# Generated by Django 5.0.6 on 2024-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_booking_new_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
